### ISSUE TITLE
FingerPrint Not really working  CM14.1

### ISSUE THREAD

**Issue by AzharNasrun** [Anik1199/android_device_xiaomi_ido#2]
- After rom installation, there is no fingerprint setup wizard.
- in setting there notification to  setup  fingerprint 
- Insert pattern/password/PIN, fingerprint not vibrate when touched

**Comment by HighwayStar** [comment]
Please attach logcat and dmesg after  boot up. If possible provide dmesg ang logcat from stock rom while using fingerprint sensor.

**Comment by scrax** [comment]
I had the fingerPrint not working between boots on first official Lineage nightly.
I've did the log when working and when not.
I've solved with a reboot. And it was not the first boot safety thing.
It was missing also the options in setup...
[no_fingerprint_work_logs.zip](https://github.com/Anik1199/android_device_xiaomi_ido/files/742581/no_fingerprint_work_logs.zip)
[fingerprint_work.zip](https://github.com/Anik1199/android_device_xiaomi_ido/files/742583/fingerprint_work.zip)

Now I'll go back to MIUI to get also those logs.

**Comment by scrax** [comment]
here the file with MIUI (fingerprint working good)
[log_miui_boot.zip](https://github.com/Anik1199/android_device_xiaomi_ido/files/742827/log_miui_boot.zip)
