### ISSUE TITLE
Camera works fine on base 13MP resolution but not on lower ones

### ISSUE THREAD

**Issue by mrigess** [Anik1199/android_device_xiaomi_ido#4]
Camera dims dark for 16:9 aspect ratio resolution (e.g. 9.7 MP) but works fine for 13MP (4:3 aspect ratio) on my Redmi 3 Pro. Note that instant switching to 9.7MP allows shooting and problem is not seen. But once you minimize/close camera app and open it back, the effect is seen. 

I guess logcat wont help here so I have added a screencast that illustrates the issue.
[https://youtu.be/mU9jSeTfhV0](url)

*Replication steps*
- It happens while using camera outdoors in presence of sunlight
- Open camera app (in 13MP)
- switch to 9.7MP (16:9) resolution
- Take snaps, it will work normally
- minimise/close the camera app
- restore/open camera app
- now screen will brighten up first and quickly dim dark afterwards

**Comment by WinKarbik** [comment]
Fixed
